system:
  admin_group:
    field_templates:
      - { template: '@SQLIEzToolbox/sqli_field_templates.html.twig', priority: 0 }
      - { template: "@SQLIEzToolbox/SelectionFromEntity/FieldType/SelectionFromEntity/view/selection_field.html.twig" }
    fielddefinition_edit_templates:
      - { template: '@SQLIEzToolbox/SelectionFromEntity/selectionDefinitionField/selection_field_type_definition.html.twig', priority: 0 }
