sqli_eztoolbox_entitymanager_homepage:
    path: /sqli-admin/entities/{tabname}
    controller: SQLIEzToolboxBundle:Entities:listAllEntities
    defaults:
        tabname: 'default'

sqli_eztoolbox_entitymanager_entity_remove_element:
    path: /sqli-admin/entity/{fqcn}/remove/{compound_id}
    defaults: { _controller: SQLIEzToolboxBundle:Entities:removeElement }

sqli_eztoolbox_entitymanager_entity_edit_element:
    path: /sqli-admin/entity/{fqcn}/edit/{compound_id}
    defaults: { _controller: SQLIEzToolboxBundle:Entities:editElement }

sqli_eztoolbox_entitymanager_entity_create_element:
    path: /sqli-admin/entity/{fqcn}/create
    defaults: { _controller: SQLIEzToolboxBundle:Entities:createElement }

sqli_eztoolbox_entitymanager_entity_export_csv:
    path: /sqli-admin/entity/{fqcn}/csv
    defaults: { _controller: SQLIEzToolboxBundle:Entities:exportCSV }

sqli_eztoolbox_entitymanager_entity_homepage_reset_filter:
    path: /sqli-admin/entity/{fqcn}/reset
    controller: SQLIEzToolboxBundle:Entities:resetFilter

# Keep this route at end
sqli_eztoolbox_entitymanager_entity_homepage:
    path: /sqli-admin/entity/{fqcn}/{sort_column}/{sort_order}
    controller: SQLIEzToolboxBundle:Entities:showEntity
    defaults:
        sort_column: 'id'
        sort_order: 'ASC'