services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SQLI\EzToolboxBundle\Command\:
        resource: "../../Command/*"

    SQLI\EzToolboxBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"

    SQLI\EzToolboxBundle\Form\:
        resource: "../../Form/*"

    SQLI\EzToolboxBundle\Services\:
        resource: '../../Services/*'

    SQLI\EzToolboxBundle\Services\Twig\:
        resource: '../../Services/Twig/*'
        tags:
            - { name: twig.extension }

    SQLI\EzToolboxBundle\QueryType\:
        resource: ../../QueryType/
        tags:
            - { name: ezpublish.query_type }

    SQLI\EzToolboxBundle\Annotations\SQLIAnnotationManager:
        arguments:
            - "Entity"
            - "%sqli_ez_toolbox.entities%"
            - "%kernel.root_dir%"
            - "@annotation_reader"


    # Handler Parameters
    SQLI\EzToolboxBundle\Services\Parameter\ParameterHandlerMaintenance:
        tags:
            - { name: sqli.parameter_handler }