parameters:
    #TODO remplacement signalslot par eventlistener
    #ezpublish.signalslot.service.content.class: SQLI\EzToolboxBundle\Services\Core\ContentService

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logDir: "%kernel.logs_dir%"
            $adminLoggerEnabled: "%sqli_ez_toolbox.admin_logger.enabled%"

#    Ibexa\Core\Helper\TranslationHelper: '@Ibexa\Core\Helper\TranslationHelper'
#    Ibexa\Core\Helper\FieldHelper: '@Ibexa\Core\Helper\FieldHelper'
    Ibexa\Core\MVC\Symfony\View\ViewManagerInterface: '@Ibexa\Bundle\Core\View\Manager'
#    Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension: '@ezpublish.twig.extension.content'

    SQLI\EzToolboxBundle\Command\:
        resource: "../../Command/*"

    SQLI\EzToolboxBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"

    SQLI\EzToolboxBundle\Form\:
        resource: "../../Form/*"

    SQLI\EzToolboxBundle\Services\:
        resource: '../../Services/*'

    SQLI\EzToolboxBundle\Services\Twig\:
        resource: '../../Services/Twig/*'
        tags:
            - { name: twig.extension }

    SQLI\EzToolboxBundle\QueryType\:
        resource: ../../QueryType/
        tags:
            - { name: ibexa.query_type }

    SQLI\EzToolboxBundle\Annotations\SQLIAnnotationManager:
        arguments:
            - "Entity"
            - "%sqli_ez_toolbox.entities%"
            - "%kernel.project_dir%"
            - "@annotation_reader"

    SQLI\EzToolboxBundle\Attributes\SQLIAttributesManager:
        arguments:
            - "Entity"
            - "%sqli_ez_toolbox.entities%"
            - "%kernel.project_dir%"

    # Handler Parameters
    SQLI\EzToolboxBundle\Services\Parameter\ParameterHandlerMaintenance:
        tags:
            - { name: sqli.parameter_handler }

    SQLI\EzToolboxBundle\FieldType\SqliToolbox\Type:
        tags:
            - { name: ibexa.field_type, alias: sqlitoolbox }
            - { name: ibexa.field_type.form_mapper.value, fieldType: sqlitoolbox }
            - { name: ibexa.field_type.indexable, alias: sqlitoolbox }

    SQLI\EzToolboxBundle\Services\Serializer\SqliToolbox\ValueNormalizer:
        tags:
            - { name: serializer.normalizer }

    SQLI\EzToolboxBundle\Services\Serializer\SqliToolbox\ValueDenormalizer:
        tags:
            - { name: serializer.denormalizer }
    SQLI\EzToolboxBundle\FieldType\SelectionFromEntity\Type:
        public: true
        tags:
            - { name: ibexa.field_type, alias: selection_from_entity }
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: selection_from_entity }
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: selection_from_entity }
            - { name: ibexa.field_type.indexable, alias: selection_from_entity  }