<?php


namespace SQLI\EzToolboxBundle\Command;
use Kaliop\eZMigrationBundle\Command\GenerateCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;

class GenerateKaliopCommand extends GenerateCommand
{

    private $outputPath = '';

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('sqli:migration:generate')
            ->addoption('path', null, InputOption::VALUE_OPTIONAL, 'The path where the generated file is written');
    }

    protected function initialize(InputInterface $input, OutputInterface $output)
    {
        $this->outputPath = $input->getOption('path');
    }


    protected function getMigrationDirectory($bundleName)
    {
        if ($this->outputPath !== null){
            $filesystem = new Filesystem();
            $isAbsolutePath = $filesystem->isAbsolutePath($this->outputPath);

            $outputFileName = '';
            if( !$isAbsolutePath ) {
                $outputFileName = '/tmp/'.$this->outputPath ;
            } else {
                $outputFileName = $this->outputPath;
            }
            return $outputFileName;
        } else {
            return '/tmp';
        }
    }
}